version: "3"

services:
  nginx:
    image: typhoon-filemaker
    container_name: 2015bernarda_typhoon-filemaker
    restart: always
    environment:
      - VIRTUAL_HOST=typhoon-filemaker.typhoon.viarezo.fr
      - LETSENCRYPT_HOST=typhoon-filemaker.typhoon.viarezo.fr
      - LETSENCRYPT_EMAIL=aymeric.bernard@student.ecp.fr

networks:
  default:
    external:
      name: nginx-proxy
